### PR TITLE
initial pub.xmmintrin sse intrinsics module

### PR DESCRIPTION
**Pull request by SRSSoftware**
For the moment, the latest bcc, the one that supports Double128, doesn't compile for me, so this module doesn't have the Double128 functions included. When bcc is fixed then it's trivial to rerun the 'Make' code to include the Double128 functions automatically.

You'll need to run the 'MakeModules' to build the module files for you.

By all means includes the zlib license that you have with all of your other modules.

### CODE REVIEW

**Comment by GWRon** [comment]
To keep the repo clean (and tidy)..it would be good.) to redo the pull request from a new branch _NOT_ including binaries (you included the debug.exe).

Else you have to download the binary on clone ...even when removed meanwhile.

Not an issue, just a suggestion.

**Comment by SRSSoftware** [comment]
Oops, my bad, my first 'pull request'. I'll clean it up by getting rid of the exee, and put it on a branch. Would it be better to create and include the module files too?

**Comment by GWRon** [comment]
It should contain everything needed...but not more than needed.

Using branches in your fork keeps your repo clean too.. if Brucey declines your submission, you could remove the branch without tainting your main branches history.

Once he accepts your code, you can remove that branch too and just update your main branches state to the one of Brucey's.

Another benefit is: instead of 15 commits à la "add file I forgot in last commit" you could do all in one with a single big commit in a new branch. This keeps things clean.

I know that I do not follow that principle too...but in theory it sounds like a good idea - which is why I do it as soon as trying to corporate with another repo.

**Comment by SRSSoftware** [comment]
Ok,
Thanks for the advice, I'll give it another go.

**Pull request closed without merging**
