### PR TITLE
public vulkan api support

### PR DESCRIPTION
**Pull request by davecamp**
Hiya,

I've been using the vulkan graphics api for the past couple of months on Linux and Windows. I'm not sure if a 2D game engine would even benefit from this low level api as the only benefits come from multi-threading the gpu commands but still I thought I'd share this part. It may come in handy if someone wants to build up a vulkan multithread cross platform renderer.

At this time I have no intention of creating a Vulkan2DDriver as I'm working on a 3D one, but you never know in the future ;-)

It's up to you if want to include it. A fair warning as there may be minor bugs as I've not tried every single command and structure, however I do have a full 3d renderer working that uses it so I feel any bugs would be corner case scenarios. If/when I find bugs I'll keep my fork up to date with the fixes etc.

### CODE REVIEW

**Comment by davecamp** [comment]
@arrays
Thanks for the heads up warning with the errors!
Hmm, you're right... it is bad practice to take advantage in this way as the compiler may get changed which then could cause problems. I've removed the file as its not needed and could be a cause of bugs in the future.
Thanks for spotting and highlighting it !!

@simple..... anything
:D
Thats just not the case in Vulkan. It's very easy to make you games SLOWER!! than previous apis as the previous drivers did a very good of managing things and going multithreaded is the only way to beat them.

My renderer is still a test bed, although it works, it's still very untidy at the moment and definitely not something I'd want to put anyone else through the agony of using at this time :D
Because it does work I'm in process of abstracting everything out to a more managable and acceptable object oriented format. Device objects, DeviceContext objects, Texture objects, Index/Vertex Buffer objects, RenderTarget objects, Shader/Uniform Objects etc which are all put in to the appropriate Descriptor obects.

**Comment by davecamp** [comment]
You queried about making it work on older gpus. Thats simply down to driver support. My renderer currently uses just the core functionality that's available so *should* work anywhere. I've only written the code to interface into Linux Xcb, Linux XLib and the Win32 window surfaces. The way Khronos have solved the multi-architecture issue is actually really good so adding additional architectures should be easy enough - its just a case of getting an instance and window handle and creating the correct surface for the rest of the gpu presentation engine to use - it's very easy to abstract this part out of sight. BUT I did need to write a TSystemDriver for each surface 'type' which relates to a specific XServer library... As I'm new to Linux I can only comment on my current development, but to get it work on Linux, and bearing in mind that you don't know the end-user system,  I needed to separate out the TLinuxSystemDriver driver. Currently I split it into TLinuxSystemXcbDriver and TLinuxSystemXlibDriver. Vulkan also currently supports Wayland, MIR and Android surfaces. I haven zero experience working with any of those so that's my current limit at this time on Linux based devices :p

At a later stage I'll add vender specific extension goodies etc.
For eg. NVidia have just released an updated driver that allows you to blit a 2d texture direct to the render target surface without a shader! That would come in handy for NVidia cards only.

Writing vulkan code is akin to writing your own driver!
Good times eh :D

**Comment by woollybah** [comment]
Cool :-)

Minor note : Raspberry Pi is also Linux, but it doesn't support Vulkan as yet.
May need to end up splitting vkOS into different parts - to ease compiler directives.

**Comment by GWRon** [comment]
As it is NG-only you are able to use

?linux and not raspi
...

this is because BCC-ng allows more powerful conditionals.

**Comment by davecamp** [comment]
Yes, I decided NG only as my renderer takes advantages of Interfaces and x64. I've not used the legacy compiler for active development for a long time now.

@pi
Or maybe in 'vulkan.bmx'

    ?not raspi
    Import "vkLoader.bmx"
    ?

?

**Comment by davecamp** [comment]
@GWRon 
I've posted an old first draft demo on my github if you wanted to take a look at how to integrate with the vulkan api. As I said above it wasn't pretty and quite repetitive with memory assigment and stuff but it was a first time effort :D

https://github.com/davecamp/VulkanFirstDemo

from the original conversation here
http://www.blitzbasic.com/Community/posts.php?topic=107397

**Comment by GWRon** [comment]
Windows-only for now?

Tried it on my Windows laptop - will raise the issue on the "demo-git-repo".

**Comment by davecamp** [comment]
This was just an early demo that I wanted to show some peeps in the 'Max forum of the complexities and differences between old APIs and newer APIs but the code is too big for the forum :roll_eyes: 
If the form could have handled the large code then I wouldn't have put it on github. The forum topic was Windows based so I though I'd post a Windows example.

When I posted the code I thought of and couldn't remember where on the 'net you asked about some code. This morning I remembered it was here so I thought I'd share it with you. It's not that I was referring to above - that's still not got for anyones eyes just yet :D

**Pull request merged**
